// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS65UPoq8qqN488urlEKW8hELPrqkTKnU',
    appId: '1:386856045505:web:891390696a77a9f12dbd40',
    messagingSenderId: '386856045505',
    projectId: 'food-app-cfd18',
    authDomain: 'food-app-cfd18.firebaseapp.com',
    storageBucket: 'food-app-cfd18.appspot.com',
    measurementId: 'G-BVLCQS0WT9',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlFpuI6SmYg3swJLbHjCJYE0X1hdYtaII',
    appId: '1:386856045505:ios:6a1a17e6c01f0e102dbd40',
    messagingSenderId: '386856045505',
    projectId: 'food-app-cfd18',
    storageBucket: 'food-app-cfd18.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlFpuI6SmYg3swJLbHjCJYE0X1hdYtaII',
    appId: '1:386856045505:ios:6a1a17e6c01f0e102dbd40',
    messagingSenderId: '386856045505',
    projectId: 'food-app-cfd18',
    storageBucket: 'food-app-cfd18.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS65UPoq8qqN488urlEKW8hELPrqkTKnU',
    appId: '1:386856045505:web:88f25d46072cfc442dbd40',
    messagingSenderId: '386856045505',
    projectId: 'food-app-cfd18',
    authDomain: 'food-app-cfd18.firebaseapp.com',
    storageBucket: 'food-app-cfd18.appspot.com',
    measurementId: 'G-V3WP0X4RN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWRUJ0y5m-EUMH2_mGxpPVY6SwuzmRI0s',
    appId: '1:386856045505:android:9d7303b474884eb42dbd40',
    messagingSenderId: '386856045505',
    projectId: 'food-app-cfd18',
    storageBucket: 'food-app-cfd18.appspot.com',
  );
}
